# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 16:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

    operations = [
        migrations.CreateModel(
            name='CustomFormFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=False, max_length=11, validators=[django.core.validators.RegexValidator(message="RUT Format without periods: '99999999-k'.", regex=b'^\\d{8}-[a-zA-Z0-9]$')], verbose_name='RUT')),
                ('user', models.OneToOneField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
